name: Make Release

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1" # Every Monday at 6:00am UTC

jobs:
  make-release:

    name: Make Release

    runs-on: macos-12

    steps:

    - name: Check out the code
      uses: actions/checkout@v3

    - name: Run release script
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        ./make_release.sh "${{ vars.UPSTREAM_REPO }}"
